user_tuple=(10,3.14,"Hello","Besant")
print("Forward Indexing")
print(user_tuple[0])
print(user_tuple[1])
print(user_tuple[2])
print(user_tuple[3])
print("Negative Indexing")
print(user_tuple[-1])
print(user_tuple[-2])
print(user_tuple[-3])
print(user_tuple[-4])