#num=int(input())
num=int(input("Enter a number:"))
name=str(input("Enter a name:"))
avg=float(input("Enter a float num:"))
isBool=int(input("Enter a number to check boolean:"))
data=input("Enter a data:")
print ("nums is:",num)
print ("string is:",name)
print ("float is:",avg)
print ("isBool is:",bool(isBool))
print ("data is:",data)
