my_list=[0,"hello",3.6,100,"google"]
print(my_list)
print("forward indexing")
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])
print("negative indexing")
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-4])
print(my_list[-5])
