f=open("file.txt")
data=f.read(15)
print("String is : ",data)
position=f.tell()
print("Current cursor position is : ",position)
position=f.seek(0)
print(position)
data=f.read()
print("String is: ",data)
f.close()
