from tkinter import *

window=Tk()
window.title("Pycharm")
window.geometry("300x400")

menubar=Menu(window)

#File menu bar
filemenu=Menu(menubar,tearoff=0)
filemenu.add_command(label="New")
filemenu.add_command(label="New scratch file")
filemenu.add_command(label="Open")
filemenu.add_command(label="Save as")
filemenu.add_command(label="Open recent")
filemenu.add_command(label="Recent Project ")
filemenu.add_command(label="close recent")
filemenu.add_separator()
filemenu.add_command(label="Settings")
filemenu.add_command(label="file properties")
filemenu.add_separator()
filemenu.add_command(label="Local history ")
filemenu.add_separator()
filemenu.add_command(label="Save all")
filemenu.add_command(label="Reload all from disk")
filemenu.add_command(label="Repair ide")
filemenu.add_command(label="invalid caches")
filemenu.add_separator()
filemenu.add_command(label="Manage ide settings")
filemenu.add_command(label="New project setup")
filemenu.add_command(label="Save file as template")
filemenu.add_separator()
filemenu.add_command(label="print")
filemenu.add_command(label="Export")
filemenu.add_separator()
filemenu.add_command(label="Power saving mode")
filemenu.add_command(label="Exit",command=window.quit)
menubar.add_cascade(label="File",menu=filemenu)
editmenu=Menu(menubar,tearoff=0)
editmenu.add_command(label="Undo")
editmenu.add_command(label="Redo")
editmenu.add_separator()
editmenu.add_command(label="Cut")
editmenu.add_command(label="copy")
editmenu.add_command(label="Paste")
editmenu.add_command(label="Delete")
editmenu.add_separator()
editmenu.add_command(label="Find")
editmenu.add_command(label="Find usages")
menubar.add_cascade(label="Edit",menu=editmenu)
viewmenu=Menu(menubar,tearoff=0)
viewmenu.add_command(label="Windows tools")
viewmenu.add_command(label="Appearance")
viewmenu.add_separator()
viewmenu.add_command(label="Quick definition")
viewmenu.add_command(label="Quick type definition")
viewmenu.add_separator()
menubar.add_cascade(label="View",menu=viewmenu)
menubar.add_cascade(label="Navigate",menu=filemenu)
menubar.add_cascade(label="Code",menu=filemenu)
menubar.add_cascade(label="Run",menu=filemenu)
menubar.add_cascade(label="Tools",menu=filemenu)
menubar.add_cascade(label="Window",menu=filemenu)
menubar.add_cascade(label="Help",menu=filemenu)
window.config(menu=menubar,bg="black")

window.mainloop()
