a=int(input("Enter a number"))
b=int(input("Enter a number"))
print("Bitwise and:",a&b)
print("Bitwise or:",a|b)
print("Bitwise xor:",a^b)
print("Bitwise not:",~a)
print("Bitwise leftshift:",a<<2)
print("Bitwise rightshift:",a>>2)
